apiVersion: apps/v1
kind: Deployment
metadata:
  name: service--collaborator
  namespace: services-develop-corporation
  labels:
    app: service--collaborator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scheme: "http"
spec:
  selector:
    matchLabels:
      app: service--collaborator
  template:
    metadata:
      labels:
        app: service--collaborator
    spec:
      #imagePullSecrets:
       # - name: docker-auth
      containers:
        - name: service--collaborator
          image: service--collaborator-img
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "dev"
          resources:
            requests:
              memory: "600Mi"
              cpu: "0.4"
            limits:
              memory: "800Mi"
              cpu: "0.8"
          ports:
            - containerPort: 9090
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: service--collaborator