apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service--collaborator-hpa
  namespace: services-develop-corporation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service--collaborator
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service--collaborator-consumer-hpa
  namespace: services-develop-corporation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service--collaborator-consumer
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
