apiVersion: v1
kind: Service
metadata:
  name: service--collaborator
  namespace: services-develop-corporation
  labels:
    java-monitoring: prometheus
    app: service--collaborator
spec:
  type: ClusterIP
  selector:
    app: service--collaborator
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5000
    - port: 9090
      name: http-monitoring-prometheus
      protocol: TCP
      targetPort: 9090

