apiVersion: v1
kind: ConfigMap
metadata:
  name: service--collaborator-cm
  namespace: services-develop-corporation
data:
  RELEASE: release/1.0.0
  CLIENT_ID: "9bced1e3-dfb4-4f6e-a6b5-d15b3887993e"
  CLIENT_SECRET: "892d848d-96dd-470e-9d94-d801e8ea3fb3"
  DATA_BASE_HOTS: "172.26.96.1"
  DATA_BASE_PORT: "3309"
  DATA_BASE_NAME: "dbCollaborator"
  DATA_BASE_CLASS_DRIVE: "com.mysql.cj.jdbc.Driver"
  DATA_BASE_PROTOCOL: "jdbc:mysql"
  DATA_BASE_USERNAME: "user"
  DATA_BASE_PASSWORD: "171513"
  SPRING_BOOT_ADMIN_USER: "admin"
  SPRING_BOOT_ADMIN_PASS: "171513"
  SPRING_BOOT_ADMIN_URL: "http://service--admin.services-develop-corporation.svc.cluster.local:80/service--admin"
