apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service--collaborator-hpa
  namespace: services-develop-corporation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service--collaborator
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 30
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30

