apiVersion: v1
kind: ConfigMap
metadata:
  name: service--collaborator-cm
  namespace: services-develop-corporation
data:
  RELEASE: release/1.0.0
  CLIENT_ID: "093b3250-351f-4dc6-af20-c7ac0cbd75d7"
  CLIENT_SECRET: "3a9c3688-1cea-482e-932c-325438bb0603"
  DATA_BASE_HOTS: "172.26.96.1"
  DATA_BASE_PORT: "3309"
  DATA_BASE_NAME: "dbcolaborador"
  DATA_BASE_CLASS_DRIVE: "com.mysql.cj.jdbc.Driver"
  DATA_BASE_PROTOCOL: "jdbc:mysql"
  DATA_BASE_USERNAME: "user"
  DATA_BASE_PASSWORD: "171513"
  SPRING_BOOT_ADMIN_USER: "admin"
  SPRING_BOOT_ADMIN_PASS: "171513"
  SPRING_BOOT_ADMIN_URL: "http://service--admin.services-develop-corporation.svc.cluster.local:80/service--admin"
